//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace base_x.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bicycles_characteristic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bicycles_characteristic()
        {
            this.Bicycle = new HashSet<Bicycle>();
        }
    
        public string Model { get; set; }
        public string Material { get; set; }
        public string Brake_type { get; set; }
        public string Seat_material { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bicycle> Bicycle { get; set; }
    }
}
