//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace base_x.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_adress
    {
        public int Adress_code { get; set; }
        public Nullable<int> Client_code { get; set; }
        public string Adress { get; set; }
        public string City { get; set; }
        public Nullable<decimal> Postal_code { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
